### PR TITLE
Chore: support Babel 6 update

### PR DESCRIPTION
**Pull request by erikjung**
This makes a few changes needed to get the generator output compatible with Babel 6.

- We now use the new Babel _preset_ NPM package.
- A `.babelrc` file is now included.
- Some modules are now acquired using `require()` instead of `import` due to a breaking change.

If someone other than myself could try running this branch version of the generator, that would be great.

***
CC @tylersticka

### CODE REVIEW

**Comment by lyzadanger** [comment]
Hi @erikjung 

I'm not convinced that babel (core) isn't a dependency. This is similar what I ran into last time you pulled this dependency out of an earlier generator :)

```
$ gulp --tasks
[13:43:45] Failed to load external module babel-core/register
[13:43:45] Failed to load external module babel/register
/Users/lyzagardner/Projects/test-patternlib/gulpfile.babel.js:3
import assemble from 'fabricator-assemble';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/opt/nodes/0.12.0/lib/node_modules/gulp-cli/index.js:120:3)
    at Liftoff.<anonymous> (/opt/nodes/0.12.0/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:192:16)
    at module.exports (/opt/nodes/0.12.0/lib/node_modules/gulp-cli/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

Do you maybe have `babel` installed globally such that it is always present? It seems like it would be an odd pattern to make a `babel` plugin not also have a dependency on `babel[-core]`.

**Comment by erikjung** [comment]
@lyzadanger What do you get when you run `npm ls --depth=1` in the directory of your generator _output_?

**Comment by lyzadanger** [comment]
[npm.txt](https://github.com/cloudfour/generator-core-patternlib/files/28491/npm.txt)

**Comment by lyzadanger** [comment]
@erikjung Thanks for your patience. The addition of the dependency has fixed the issue on my current system. I'll try again after upgrading to El Capitan, etc.

**Comment by erikjung** [comment]
@lyzadanger Is this good to merge then?

**Comment by lyzadanger** [comment]
@erikjung I haven't cloned this since my system exploded. Let me try to make some time today to try doing that and checking out this branch...sorry this got lost in the shuffle :(

**Comment by lyzadanger** [comment]
I found another issue but I'll open a different issue as it's unrelated :).

*This* issue is fixed; I now get:

```
lyza@rigel:~/Projects/test-generator
$ gulp --tasks
[09:47:29] Requiring external module babel-core/register
[09:47:31] Using gulpfile ~/Projects/test-generator/gulpfile.babel.js
[09:47:31] Tasks for ~/Projects/test-generator/gulpfile.babel.js
[09:47:31] ├── clean
[09:47:31] ├── css
[09:47:31] ├── js
[09:47:31] ├── serve
[09:47:31] ├── watch
[09:47:31] ├── assemble
[09:47:31] ├─┬ frontend
[09:47:31] │ ├── assemble
[09:47:31] │ ├── css
[09:47:31] │ └── js
[09:47:31] └─┬ default
[09:47:31]   └── frontend
```

:+1:

**Pull request merged**
